//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.02 at 02:04:07 PM CET 
//


package com.example.demo.bean;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="class"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="classTeacher" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="student"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="classId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clazz",
    "student"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(name = "class", required = true)
    protected Root.Class clazz;
    @XmlElement(required = true)
    protected Root.Student student;

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Class }
     *     
     */
    public Root.Class getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Class }
     *     
     */
    public void setClazz(Root.Class value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the student property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Student }
     *     
     */
    public Root.Student getStudent() {
        return student;
    }

    /**
     * Sets the value of the student property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Student }
     *     
     */
    public void setStudent(Root.Student value) {
        this.student = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="classTeacher" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "className",
        "classTeacher",
        "room"
    })
    public static class Class {

        @XmlElement(required = true)
        protected Object className;
        @XmlElement(required = true)
        protected Object classTeacher;
        @XmlSchemaType(name = "unsignedByte")
        protected short room;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setClassName(Object value) {
            this.className = value;
        }

        /**
         * Gets the value of the classTeacher property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getClassTeacher() {
            return classTeacher;
        }

        /**
         * Sets the value of the classTeacher property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setClassTeacher(Object value) {
            this.classTeacher = value;
        }

        /**
         * Gets the value of the room property.
         * 
         */
        public short getRoom() {
            return room;
        }

        /**
         * Sets the value of the room property.
         * 
         */
        public void setRoom(short value) {
            this.room = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="classId" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "age",
        "classId",
        "name",
        "picture"
    })
    public static class Student {

        @XmlElement(required = true)
        protected BigDecimal age;
        @XmlSchemaType(name = "unsignedByte")
        protected short classId;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected byte[] picture;

        /**
         * Gets the value of the age property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAge() {
            return age;
        }

        /**
         * Sets the value of the age property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAge(BigDecimal value) {
            this.age = value;
        }

        /**
         * Gets the value of the classId property.
         * 
         */
        public short getClassId() {
            return classId;
        }

        /**
         * Sets the value of the classId property.
         * 
         */
        public void setClassId(short value) {
            this.classId = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the picture property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getPicture() {
            return picture;
        }

        /**
         * Sets the value of the picture property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setPicture(byte[] value) {
            this.picture = value;
        }

    }

}
